export const productDatas = [
  {
    name: "Black Cotton Leggins",
    price: "1000",
    img: "https://th.bing.com/th/id/OIP.i_ocXC6wjNXf2AtwbaD1WQHaHa?w=151&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "L",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "grey",
  },
  {
    name: "Churidar Piece",
    price: "1785",
    img: "https://th.bing.com/th?id=OIP.G0Wxso0Om8yxty1tUYIrPQHaKD&w=214&h=291&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    size: "M",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "orange",
  },
  {
    name: "Top and Jeans",
    price: "2580",
    img: "https://th.bing.com/th?id=OIP.t9GT-t65BYEcpiPwEjllvAHaHa&w=250&h=250&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    size: "S",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "yellow",
  },
  {
    name: "Tshirt Material",
    price: "1000",
    img: "https://th.bing.com/th/id/OIP.Mh0d55WTV2KzHzggxbu_iwHaHa?w=215&h=215&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "XL",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "green",
  },
  {
    name: "Casual Shirt",
    price: "700",
    img: "https://th.bing.com/th/id/OIP.lzzI8bCgWJ3toNIDfsV7egHaIq?w=153&h=186&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "XS",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "black",
  },
  {
    name: "Women Sarees",
    price: "1000",
    img: "https://th.bing.com/th/id/OIP.MiyyAer9nBtDOjCM_c1zLAHaJQ?w=143&h=186&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "L",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "green",
  },
  {
    name: "Cotton Dress",
    price: "4399",
    img: "https://th.bing.com/th/id/OIP.WpzWMFxM82-rdcdUnk3lgQAAAA?w=115&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "L",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "yellow",
  },
  {
    name: "Lahanthi",
    price: "7329",
    img: "https://th.bing.com/th/id/OIP.oM7hlRKk4z7CNit7sG2LTQHaHa?w=179&h=186&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "XL",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "grey",
  },
  {
    name: "Pant and Tshirt",
    price: "8000",
    img: "https://th.bing.com/th/id/OIP.dFrkbKlcYX1PufkO7YyuUQHaHN?w=180&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "XS",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "grey",
  },
  {
    name: "Black Cotton Leggins",
    price: "9000",
    img: "https://th.bing.com/th/id/OIP.Ylpabhn2mgTHn4wrVCi5EAAAAA?w=132&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "L",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "black",
  },
  {
    name: "Dupatta",
    price: "4300",
    img: "https://th.bing.com/th/id/OIP.hOZKP-9OOlvdzrPqz0zW2AHaEo?w=312&h=195&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "M",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "yellow",
  },
  {
    name: "Men Baniyan's",
    price: "1000",
    img: "https://th.bing.com/th?id=OIP.bCQfrLT6HDXnRL_fMvLVogAAAA&w=216&h=288&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    size: "XS",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "grey",
  },
  {
    name: "Pant and Tshirt",
    price: "8000",
    img: "https://th.bing.com/th/id/OIP.dFrkbKlcYX1PufkO7YyuUQHaHN?w=180&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "XS",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "green",
  },
  {
    name: "Black Cotton Leggins",
    price: "9000",
    img: "https://th.bing.com/th/id/OIP.Ylpabhn2mgTHn4wrVCi5EAAAAA?w=132&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "L",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "black",
  },
  {
    name: "Dupatta",
    price: "4300",
    img: "https://th.bing.com/th/id/OIP.hOZKP-9OOlvdzrPqz0zW2AHaEo?w=312&h=195&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "M",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "black",
  },
  {
    name: "Men Baniyan's",
    price: "1000",
    img: "https://th.bing.com/th?id=OIP.bCQfrLT6HDXnRL_fMvLVogAAAA&w=216&h=288&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    size: "XS",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "black",
  },


  {
    name: "Churidar Piece",
    price: "1785",
    img: "https://th.bing.com/th?id=OIP.G0Wxso0Om8yxty1tUYIrPQHaKD&w=214&h=291&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    size: "M",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "orange",
  },
  {
    name: "Top and Jeans",
    price: "2580",
    img: "https://th.bing.com/th?id=OIP.t9GT-t65BYEcpiPwEjllvAHaHa&w=250&h=250&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    size: "S",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "yellow",
  },
  {
    name: "Tshirt Material",
    price: "1000",
    img: "https://th.bing.com/th/id/OIP.Mh0d55WTV2KzHzggxbu_iwHaHa?w=215&h=215&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    size: "XL",
    desc: "What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    color: "green",
  },
];
